///////////////////////////////////////////////////////////
//  Find Company DA.cs
//  Implementation of the Class Find Company DA
//  Generated by Enterprise Architect
//  Created on:      26-Nov-2019 12:04:10 PM
//  Original author: miraj
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DataSetTableAdapters;




public class FindCompany{

	private int companyId;
	private string companyName;
    private string companyType;

	public FindCompany(){

	}

	~FindCompany(){

	}
    public void addCompany(int comID, string comName,string compType)
    {
        FindCompanyDaTableAdapter cp = new FindCompanyDaTableAdapter();
        cp.addCompany(comID, comName,compType);
    }
    public void findCompanyInfo(string comType){

       

	}

	public void getCompanyList(){

	}

	public void selectCompany(){

	}

}//end Find Company DA